[workspace]
resolver = "2"
members = ["codexfs-fuse", "codexfs-core", "codexfs-mkfs"]


[workspace.dependencies]
codexfs-core = { path = "./codexfs-core/" }
clap = { version = "4.5", features = ["derive"] }
fuser = "0.15"
libc = "0.2"
log = "0.4"
bitflags = "2.8"
num-traits = "0.2"
