[package]
name = "codexfs-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
codexfs-core = { path = "../codexfs-core/" }

fuser = "0.15"
libc = "0.2"
log = "0.4"
clap = { version = "4.5", features = ["derive"] }
