[package]
name = "codexfs-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
codexfs-core = { workspace = true }

fuser = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
