[package]
name = "codexfs-fuse"
version = "0.1.0"
edition = "2024"

[dependencies]
codexfs-core = { workspace = true }

fuser = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
bytemuck = { workspace = true }
