[package]
name = "codexfs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
bitflags = { workspace = true }
num-traits = { workspace = true }
bytemuck = { workspace = true }
libc = { workspace = true }
anyhow = { workspace = true }
